# @package model
_target_: maze.perception.models.template_model_composer.TemplateModelComposer

distribution_mapper_config: []

model_builder:
  _target_: maze.perception.builders.ConcatModelBuilder

  observation_modality_mapping:
    cart_position: feature
    cart_velocity: feature
    pole_angle: feature
    pole_angular_velocity: feature


  modality_config:
    feature:
      block_type: maze.perception.blocks.DenseBlock
      block_params:
        hidden_units: [4]
        non_lin: torch.nn.Tanh
    hidden:
      block_type: maze.perception.blocks.DenseBlock
      block_params:
        hidden_units: [128, 128]
        non_lin: torch.nn.Tanh
    recurrence: {}

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer

critic:
  _target_: maze.perception.models.critics.SharedStateCriticComposer