# @package model
_target_: maze.perception.models.custom_model_composer.CustomModelComposer

distribution_mapper_config: []

policy:
  _target_: maze.perception.models.policies.ProbabilisticPolicyComposer
  networks:
  - _target_: maze_cartpole.models.actor.CartPolePolicyNet
    non_lin: torch.nn.Tanh
  separated_agent_networks: False

# No critic by default
critic: ~
